name: Build and Publish

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9, 3.10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy

      - name: Install Fortran compiler on Ubuntu
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install -y gfortran

      - name: Install Fortran compiler on Windows
        if: matrix.os == 'windows-latest'
        run: choco install mingw --version=8.1.0

      - name: Install Fortran compiler on macOS
        if: matrix.os == 'macos-latest'
        run: brew install gcc

      - name: Build the package
        run: |
          pip install wheel
          python setup.py bdist_wheel

      - name: Audit wheels for manylinux (Linux only)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pip install auditwheel
          auditwheel repair dist/*.whl

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheel
          path: dist/*.whl
